/* data.js — the product catalog. Kept in a global so both automation
   scripts and page code can query it (e.g. window.CATALOG in tests). */

window.CATALOG = [
  {
    id: 1, sku: 'AUD-101', name: 'Aurora Wireless Headphones',
    category: 'Electronics', tags: ['audio', 'wireless'],
    price: 89.99, oldPrice: 129.99, rating: 4.7, reviewCount: 214, stock: 42,
    image: '../images/product-headphones.svg', badge: 'sale',
    sizes: [], colors: ['Purple', 'Black', 'White'],
    description: 'Studio-grade wireless over-ear headphones with active noise cancellation, 40 hour battery life and pillow-soft memory foam earcups. Delivers rich, balanced sound whether you are on a call, tracking a mix or unwinding on a long-haul flight.',
    specs: {
      'Type': 'Over-ear wireless',
      'Battery': '40 hours',
      'Connectivity': 'Bluetooth 5.3 + 3.5 mm',
      'ANC': 'Adaptive dual-mic',
      'Weight': '248 g',
      'Warranty': '2 years',
    },
  },
  {
    id: 2, sku: 'WCH-202', name: 'Nova Smart Watch Series 8',
    category: 'Electronics', tags: ['wearable', 'fitness'],
    price: 149.99, oldPrice: 199.99, rating: 4.6, reviewCount: 388, stock: 27,
    image: '../images/product-smartwatch.svg', badge: 'hot',
    sizes: ['40 mm', '44 mm'], colors: ['Space Grey', 'Silver', 'Rose Gold'],
    description: 'Track every heart-beat, workout and sleep cycle on a bright always-on AMOLED display. Nova Series 8 pairs with iOS and Android, is IP68 waterproof, and lasts a full week on a charge.',
    specs: {
      'Display': '1.4" AMOLED',
      'Battery': '7 days',
      'GPS': 'Built-in',
      'Water rating': '5 ATM',
      'Sensors': 'HR • SpO2 • Skin temp',
      'Warranty': '1 year',
    },
  },
  {
    id: 3, sku: 'SPK-303', name: 'Boom Bluetooth Speaker',
    category: 'Electronics', tags: ['audio', 'party'],
    price: 59.99, oldPrice: null, rating: 4.4, reviewCount: 156, stock: 88,
    image: '../images/product-speaker.svg', badge: 'new',
    sizes: [], colors: ['Orange', 'Black'],
    description: 'Compact yet loud. 30 W of stereo output, 24 hour battery, and pair two Booms together for room-filling sound. IPX7 waterproof — take it to the pool without a second thought.',
    specs: {
      'Output': '30 W stereo',
      'Battery': '24 hours',
      'Waterproof': 'IPX7',
      'Bluetooth': '5.2',
      'Aux-in': 'Yes',
      'Warranty': '1 year',
    },
  },
  {
    id: 4, sku: 'JKT-404', name: 'Ranger Leather Jacket',
    category: 'Fashion', tags: ['outerwear'],
    price: 199.99, oldPrice: 259.00, rating: 4.8, reviewCount: 97, stock: 14,
    image: '../images/product-leather-jacket.svg', badge: 'sale',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Brown', 'Black'],
    description: 'Full-grain cowhide leather, hand-stitched, with a quilted satin lining and brass hardware. A jacket that only gets better after every wear.',
    specs: {
      'Material': '100% full-grain leather',
      'Lining': 'Quilted satin',
      'Zipper': 'YKK brass',
      'Pockets': '4 (2 outer, 2 inner)',
      'Care': 'Dry clean only',
      'Warranty': '1 year',
    },
  },
  {
    id: 5, sku: 'SHO-505', name: 'AirRunner Pro Running Shoes',
    category: 'Fashion', tags: ['footwear', 'sports'],
    price: 79.99, oldPrice: 99.99, rating: 4.5, reviewCount: 512, stock: 63,
    image: '../images/product-running-shoes.svg', badge: null,
    sizes: ['6', '7', '8', '9', '10', '11', '12'], colors: ['Green', 'Blue', 'Grey'],
    description: 'Lightweight cushioned midsole with breathable knit upper. Springy energy return that keeps you fresh mile after mile.',
    specs: {
      'Weight': '260 g / shoe',
      'Drop': '8 mm',
      'Upper': 'Engineered knit',
      'Midsole': 'Responsive EVA',
      'Outsole': 'Rubber grip',
      'Warranty': '6 months',
    },
  },
  {
    id: 6, sku: 'ACC-606', name: 'Solstice UV400 Sunglasses',
    category: 'Fashion', tags: ['accessories'],
    price: 39.99, oldPrice: 59.99, rating: 4.3, reviewCount: 71, stock: 132,
    image: '../images/product-sunglasses.svg', badge: 'sale',
    sizes: [], colors: ['Amber', 'Black', 'Rose'],
    description: 'Polarised UV400 lenses in a lightweight polymer frame. Blocks glare, keeps the world sharp — and looks unreasonably good doing it.',
    specs: {
      'UV rating': 'UV400',
      'Lens': 'Polarised',
      'Frame': 'TR90 polymer',
      'Weight': '22 g',
      'Includes': 'Hard case + cloth',
      'Warranty': '1 year',
    },
  },
  {
    id: 7, sku: 'HOM-707', name: 'Barista Pro Coffee Maker',
    category: 'Home', tags: ['kitchen'],
    price: 129.99, oldPrice: null, rating: 4.6, reviewCount: 189, stock: 21,
    image: '../images/product-coffee-maker.svg', badge: 'hot',
    sizes: [], colors: ['Copper', 'Steel'],
    description: '15-bar Italian pump, integrated milk frother, and a programmable clock so you wake up to the smell of espresso. Barista Pro turns your kitchen into a café.',
    specs: {
      'Pressure': '15 bar',
      'Capacity': '1.8 L',
      'Frother': 'Steam wand',
      'Timer': 'Programmable',
      'Cup warmer': 'Yes',
      'Warranty': '2 years',
    },
  },
  {
    id: 8, sku: 'HOM-808', name: 'Halo Ambient Table Lamp',
    category: 'Home', tags: ['lighting', 'decor'],
    price: 45.99, oldPrice: 59.99, rating: 4.5, reviewCount: 64, stock: 40,
    image: '../images/product-table-lamp.svg', badge: null,
    sizes: [], colors: ['Rose', 'Sand', 'Slate'],
    description: 'A warm 2700 K LED bulb in a hand-thrown ceramic base. Touch-dim across three brightness levels — perfect for reading nooks or bedside tables.',
    specs: {
      'Bulb': '9 W LED (2700 K)',
      'Dimming': '3 levels touch',
      'Base': 'Hand-thrown ceramic',
      'Cable': '1.8 m braided',
      'Rated life': '25,000 h',
      'Warranty': '2 years',
    },
  },
  {
    id: 9, sku: 'HOM-909', name: 'Master Chef Knives Set (6-pc)',
    category: 'Home', tags: ['kitchen'],
    price: 89.99, oldPrice: 119.99, rating: 4.7, reviewCount: 231, stock: 17,
    image: '../images/product-knives-set.svg', badge: null,
    sizes: [], colors: ['Steel/Black'],
    description: 'German high-carbon stainless steel. Ergonomic hardwood handles. Comes with chef, santoku, bread, utility, paring knives and honing rod.',
    specs: {
      'Set': '6 pieces + rod',
      'Blade': 'High-carbon steel',
      'Handle': 'Pakkawood',
      'Balance': 'Full tang',
      'Care': 'Hand-wash',
      'Warranty': 'Lifetime',
    },
  },
  {
    id: 10, sku: 'BOK-010', name: 'JavaScript — The Complete Guide',
    category: 'Books', tags: ['programming'],
    price: 34.99, oldPrice: 49.99, rating: 4.9, reviewCount: 812, stock: 200,
    image: '../images/product-js-book.svg', badge: 'hot',
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'The definitive reference for modern JavaScript. Covers ES2015 through ES2025, async patterns, TypeScript interop and browser APIs.',
    specs: {
      'Pages': '842',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '5th (2026)',
      'ISBN': '978-1-2345-6789-0',
      'Warranty': 'N/A',
    },
  },
  {
    id: 11, sku: 'BOK-011', name: 'Design Handbook 2026',
    category: 'Books', tags: ['design'],
    price: 29.99, oldPrice: null, rating: 4.7, reviewCount: 143, stock: 92,
    image: '../images/product-design-book.svg', badge: 'new',
    sizes: ['Paperback', 'Hardcover'], colors: [],
    description: 'A visual playbook of typographic systems, colour theory and layout patterns used by leading product studios in 2026.',
    specs: {
      'Pages': '318 (full colour)',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '2nd',
      'ISBN': '978-1-2345-6790-6',
      'Warranty': 'N/A',
    },
  },
  {
    id: 12, sku: 'BOK-012', name: 'Timeless Novels Box Set (4 vols)',
    category: 'Books', tags: ['fiction'],
    price: 24.99, oldPrice: 39.99, rating: 4.6, reviewCount: 78, stock: 34,
    image: '../images/product-novel-set.svg', badge: 'sale',
    sizes: [], colors: [],
    description: 'A curated box set of four unabridged classics — jacketed hardcovers with satin ribbons and matching slipcase.',
    specs: {
      'Volumes': '4 hardcovers',
      'Total pages': '1,940',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'ISBN': '978-1-2345-6791-3',
      'Warranty': 'N/A',
    },
  },
  {
    id: 13, sku: 'ELE-013', name: 'Apple iPhone 16 Pro',
    category: 'Electronics', tags: ['phone', 'apple', '5g'],
    price: 1099.00, oldPrice: 1199.00, rating: 4.8, reviewCount: 1420, stock: 45,
    image: '../images/product-iphone.svg', badge: 'new',
    sizes: ['128 GB', '256 GB', '512 GB', '1 TB'],
    colors: ['Natural Titanium', 'Blue Titanium', 'White Titanium', 'Black Titanium'],
    description: 'The iPhone 16 Pro brings a titanium frame, a brighter 6.3-inch ProMotion display, the A18 Pro chip, and a redesigned pro camera system with a 5x tetraprism telephoto. Action button + capture control put your favourite shortcuts one press away.',
    specs: {
      'Display': '6.3" LTPO ProMotion OLED, 120 Hz',
      'Chip': 'Apple A18 Pro',
      'Rear camera': '48 MP main + 48 MP UW + 12 MP 5x tele',
      'Front camera': '12 MP TrueDepth',
      'Battery': 'Up to 27 h video playback',
      'Connectivity': '5G, Wi-Fi 7, USB-C (Thunderbolt)',
      'OS': 'iOS 18',
      'Warranty': '1 year Apple limited',
    },
  },
  {
    id: 14, sku: 'ELE-014', name: 'Samsung Galaxy S25 Ultra',
    category: 'Electronics', tags: ['phone', 'samsung', 's-pen'],
    price: 1299.00, oldPrice: 1399.00, rating: 4.7, reviewCount: 987, stock: 32,
    image: '../images/product-galaxy.svg', badge: 'hot',
    sizes: ['256 GB', '512 GB', '1 TB'],
    colors: ['Titanium Gray', 'Titanium Black', 'Titanium Silverblue', 'Titanium Whitesilver'],
    description: 'A 6.9-inch QHD+ Dynamic AMOLED display, built-in S Pen, quad-camera system with a 200 MP main sensor and 100x Space Zoom, and Snapdragon 8 Elite for Galaxy — designed for creators who don’t compromise.',
    specs: {
      'Display': '6.9" QHD+ Dynamic AMOLED 2X, 120 Hz',
      'Chip': 'Snapdragon 8 Elite for Galaxy',
      'Rear camera': '200 MP + 50 MP UW + 50 MP 5x + 10 MP 3x',
      'Front camera': '12 MP',
      'Battery': '5,000 mAh, 45 W wired',
      'S Pen': 'Included (built in)',
      'OS': 'Android 15 · One UI 7',
      'Warranty': '1 year',
    },
  },
  {
    id: 15, sku: 'ELE-015', name: 'Apple iPad Pro 13" (M5)',
    category: 'Electronics', tags: ['tablet', 'apple', 'creative'],
    price: 899.00, oldPrice: 999.00, rating: 4.9, reviewCount: 612, stock: 40,
    image: '../images/product-ipad.svg', badge: 'sale',
    sizes: ['256 GB', '512 GB', '1 TB', '2 TB'],
    colors: ['Space Black', 'Silver'],
    description: 'The thinnest iPad ever, powered by the M5 chip and a stunning Ultra Retina XDR tandem-OLED display. Draw, edit ProRes footage, or run pro apps on a machine that is barely 5 mm thick and Apple Pencil Pro ready.',
    specs: {
      'Display': '13" Ultra Retina XDR tandem OLED, 120 Hz',
      'Chip': 'Apple M5 (10-core CPU)',
      'Rear camera': '12 MP wide + LiDAR',
      'Front camera': '12 MP landscape',
      'Connectivity': 'Wi-Fi 7, USB-C (Thunderbolt 4)',
      'Accessories': 'Apple Pencil Pro, Magic Keyboard',
      'OS': 'iPadOS 18',
      'Warranty': '1 year',
    },
  },
  {
    id: 16, sku: 'ELE-016', name: 'Apple MacBook Air 15" (M4)',
    category: 'Electronics', tags: ['laptop', 'apple', 'ultrabook'],
    price: 1349.00, oldPrice: 1499.00, rating: 4.8, reviewCount: 730, stock: 22,
    image: '../images/product-macbook.svg', badge: 'new',
    sizes: ['16 GB / 512 GB', '24 GB / 1 TB', '32 GB / 2 TB'],
    colors: ['Midnight', 'Starlight', 'Space Gray', 'Silver'],
    description: 'Silent, fanless, and impossibly thin — the 15-inch MacBook Air with the M4 chip delivers pro-grade performance and up to 20 hours of battery life in a 1.51 kg body.',
    specs: {
      'Display': '15.3" Liquid Retina, 500 nits, P3',
      'Chip': 'Apple M4 (10-core CPU, 10-core GPU)',
      'Memory': '16 GB unified (up to 32 GB)',
      'Storage': '512 GB SSD (up to 2 TB)',
      'Battery': 'Up to 20 h wireless web',
      'Ports': '2× TB4, MagSafe 3, 3.5 mm',
      'OS': 'macOS Sequoia',
      'Warranty': '1 year',
    },
  },
  {
    id: 17, sku: 'ELE-017', name: 'Google Pixel 10 Pro',
    category: 'Electronics', tags: ['phone', 'google', 'ai'],
    price: 999.00, oldPrice: null, rating: 4.6, reviewCount: 421, stock: 55,
    image: '../images/product-pixel.svg', badge: 'new',
    sizes: ['128 GB', '256 GB', '512 GB'],
    colors: ['Obsidian', 'Porcelain', 'Bay', 'Rose Quartz'],
    description: 'Powered by the Tensor G5 chip and Gemini Nano running on-device, Pixel 10 Pro brings smarter photo editing, live translation, and a triple camera system built around Google’s computational imaging.',
    specs: {
      'Display': '6.7" LTPO OLED, 120 Hz',
      'Chip': 'Google Tensor G5',
      'Rear camera': '50 MP + 48 MP UW + 48 MP 5x tele',
      'Front camera': '42 MP',
      'Battery': '5,050 mAh, 30 W wired',
      'AI': 'On-device Gemini Nano',
      'OS': 'Android 15',
      'Warranty': '7 years OS updates',
    },
  },
  {
    id: 18, sku: 'ELE-018', name: 'Dell XPS 15 (2026)',
    category: 'Electronics', tags: ['laptop', 'windows', 'creator'],
    price: 1699.00, oldPrice: 1899.00, rating: 4.5, reviewCount: 289, stock: 15,
    image: '../images/product-laptop.svg', badge: 'sale',
    sizes: ['16 GB / 512 GB', '32 GB / 1 TB', '64 GB / 2 TB'],
    colors: ['Platinum Silver', 'Graphite'],
    description: 'A 15.6-inch OLED touch display, Intel Core Ultra 9 with a dedicated NPU, and an NVIDIA RTX 4070 — the XPS 15 is a portable studio for photo, video and 3D work.',
    specs: {
      'Display': '15.6" 3.5K OLED touch, 120 Hz',
      'CPU': 'Intel Core Ultra 9 285H',
      'GPU': 'NVIDIA GeForce RTX 4070 (8 GB)',
      'Memory': '32 GB DDR5 (up to 64 GB)',
      'Storage': '1 TB NVMe SSD',
      'Battery': '86 Wh, up to 13 h',
      'OS': 'Windows 11 Pro',
      'Warranty': '1 year Premium Support',
    },
  },
  {
    id: 19, sku: 'ELE-019', name: 'Nintendo Switch 2 OLED',
    category: 'Electronics', tags: ['gaming', 'console', 'nintendo'],
    price: 449.00, oldPrice: null, rating: 4.7, reviewCount: 1834, stock: 88,
    image: '../images/product-switch.svg', badge: 'hot',
    sizes: ['64 GB Standard', '256 GB Special Edition'],
    colors: ['Neon Red / Blue', 'Classic Black', 'Pastel'],
    description: 'The next-generation Switch adds a bigger 8-inch OLED screen, DLSS-powered upscaling in docked mode, and magnetic Joy-Con 2 controllers that snap on with a satisfying click. Backwards compatible with your Switch library.',
    specs: {
      'Display': '8" OLED, 1080p, VRR',
      'Docked output': 'Up to 4K 60 fps with DLSS',
      'Storage': '64 GB internal + microSD Express',
      'Battery': '4.5 – 9 h',
      'Controllers': 'Joy-Con 2 (magnetic, HD rumble+)',
      'Backwards compat': 'Physical & digital Switch 1 titles',
      'Warranty': '1 year',
    },
  },
  {
    id: 20, sku: 'ELE-020', name: 'Sony PlayStation 5 Slim',
    category: 'Electronics', tags: ['gaming', 'console', 'sony'],
    price: 499.00, oldPrice: 549.00, rating: 4.8, reviewCount: 2103, stock: 40,
    image: '../images/product-ps5.svg', badge: 'sale',
    sizes: ['1 TB Disc', '1 TB Digital'],
    colors: ['White', 'Midnight Black'],
    description: 'A 30 % smaller PS5 with a detachable Ultra HD Blu-ray drive and a 1 TB SSD out of the box. 4K gaming with ray-tracing, 3D audio, and haptic DualSense triggers — same great console, sleeker chassis.',
    specs: {
      'CPU': 'AMD Zen 2, 8 cores @ 3.5 GHz',
      'GPU': 'AMD RDNA 2, 10.28 TFLOPs',
      'Memory': '16 GB GDDR6',
      'Storage': '1 TB custom SSD',
      'Video out': '4K 120 Hz, 8K support, HDR10',
      'Controller': 'DualSense (haptic triggers, 3D audio)',
      'Warranty': '1 year',
    },
  },

  /* -------- Electronics fillers (21-24) so category has 15 -------- */
  {
    id: 21, sku: 'ELE-021', name: 'Sonic AirPods Pro 3',
    category: 'Electronics', tags: ['audio', 'earbuds', 'anc'],
    price: 249.00, oldPrice: 279.00, rating: 4.7, reviewCount: 612, stock: 74,
    image: '../images/product-earbuds.svg', badge: 'hot',
    sizes: [], colors: ['White', 'Black'],
    description: 'Third-generation earbuds with adaptive audio, personalised spatial sound, and up to 6 hours of listening per charge. USB-C MagSafe case adds 30 hours on the go.',
    specs: {
      'Type': 'True wireless in-ear',
      'ANC': 'Adaptive, 2x quieter',
      'Battery': '6 h (30 h with case)',
      'Connectivity': 'Bluetooth 5.3',
      'Water rating': 'IPX4 buds, IPX4 case',
      'Warranty': '1 year',
    },
  },
  {
    id: 22, sku: 'ELE-022', name: 'Lumen 4K Studio Webcam',
    category: 'Electronics', tags: ['webcam', 'streaming', 'wfh'],
    price: 189.00, oldPrice: 219.00, rating: 4.5, reviewCount: 243, stock: 52,
    image: '../images/product-webcam.svg', badge: 'sale',
    sizes: [], colors: ['Space Grey'],
    description: '4K UHD sensor with AI framing, dual noise-cancelling mics, and a magnetic privacy shutter. Plugs into any USB-C port and works with Zoom, Meet and Teams.',
    specs: {
      'Resolution': '4K 60 fps / 1080p 120 fps',
      'Field of view': '90 degrees',
      'Mic': 'Dual beamforming w/ noise cancel',
      'Connection': 'USB-C 3.2',
      'Privacy': 'Magnetic lens shutter',
      'Warranty': '2 years',
    },
  },
  {
    id: 23, sku: 'ELE-023', name: 'MeshNet Wi-Fi 7 Router (3-pack)',
    category: 'Electronics', tags: ['networking', 'wifi7', 'mesh'],
    price: 599.00, oldPrice: 699.00, rating: 4.6, reviewCount: 187, stock: 30,
    image: '../images/product-router.svg', badge: 'new',
    sizes: ['2-pack', '3-pack'], colors: ['White'],
    description: 'Whole-home Wi-Fi 7 mesh with 6 GHz backhaul. Blankets homes up to 8,000 sq ft with tri-band gigabit speed and self-healing network intelligence.',
    specs: {
      'Standard': 'Wi-Fi 7 (802.11be), tri-band',
      'Speed': 'Up to 21 Gbps',
      'Coverage': 'Up to 8,000 sq ft (3-pack)',
      'Ports': '2.5 GbE WAN + 3x 2.5 GbE LAN',
      'Security': 'WPA3, guest network, VLAN',
      'Warranty': '2 years',
    },
  },
  {
    id: 24, sku: 'ELE-024', name: 'VoltEdge 32" 4K Gaming Monitor',
    category: 'Electronics', tags: ['monitor', 'gaming', '4k'],
    price: 649.00, oldPrice: 799.00, rating: 4.7, reviewCount: 356, stock: 18,
    image: '../images/product-monitor.svg', badge: 'sale',
    sizes: ['27 inch', '32 inch'], colors: ['Black'],
    description: '32-inch 4K IPS panel with 165 Hz refresh, 1 ms GtG response and HDR600. Includes KVM, USB-C 90 W passthrough and a height-adjustable ergonomic stand.',
    specs: {
      'Panel': '32" 4K UHD IPS',
      'Refresh': '165 Hz, 1 ms GtG',
      'HDR': 'DisplayHDR 600, DCI-P3 98%',
      'Ports': 'DP 1.4, 2x HDMI 2.1, USB-C 90 W',
      'Ergonomics': 'Height, tilt, swivel, pivot',
      'Warranty': '3 years',
    },
  },

  /* -------- Fashion fillers (25-36) so category has 15 -------- */
  {
    id: 25, sku: 'FSH-025', name: 'Slim-fit Denim Jeans',
    category: 'Fashion', tags: ['denim', 'bottoms'],
    price: 59.99, oldPrice: 79.99, rating: 4.5, reviewCount: 421, stock: 210,
    image: '../images/product-jeans.svg', badge: 'sale',
    sizes: ['28', '30', '32', '34', '36', '38'], colors: ['Indigo', 'Black', 'Stone'],
    description: 'Mid-rise stretch denim with a slim tapered leg. Comfortable enough for a long commute, dressy enough for dinner.',
    specs: {
      'Material': '98% cotton, 2% elastane',
      'Rise': 'Mid',
      'Fit': 'Slim tapered',
      'Wash': 'Machine wash cold',
      'Origin': 'Ethically sourced denim',
      'Warranty': '6 months seams',
    },
  },
  {
    id: 26, sku: 'FSH-026', name: 'Merino Wool Crew Sweater',
    category: 'Fashion', tags: ['knitwear', 'wool'],
    price: 89.99, oldPrice: 119.00, rating: 4.7, reviewCount: 178, stock: 68,
    image: '../images/product-sweater.svg', badge: 'new',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Charcoal', 'Ivory', 'Burgundy'],
    description: 'Ultra-soft 18.5-micron merino, machine washable, and temperature regulating. Layer alone or under a jacket.',
    specs: {
      'Material': '100% merino wool',
      'Fibre gauge': '18.5 micron',
      'Weight': '340 gsm',
      'Fit': 'Regular',
      'Care': 'Machine wash cool',
      'Warranty': '1 year',
    },
  },
  {
    id: 27, sku: 'FSH-027', name: 'Chelsea Leather Boots',
    category: 'Fashion', tags: ['footwear', 'leather'],
    price: 149.99, oldPrice: 189.00, rating: 4.6, reviewCount: 234, stock: 48,
    image: '../images/product-boots.svg', badge: null,
    sizes: ['7', '8', '9', '10', '11', '12'], colors: ['Chocolate', 'Black'],
    description: 'Full-grain calf leather chelsea boots with elastic side gussets and a Goodyear-welted rubber sole. Timeless, hard-wearing.',
    specs: {
      'Upper': 'Full-grain calf leather',
      'Lining': 'Leather',
      'Sole': 'Goodyear welted rubber',
      'Heel': '3 cm',
      'Care': 'Wax polish monthly',
      'Warranty': '1 year',
    },
  },
  {
    id: 28, sku: 'FSH-028', name: 'Classic Baseball Cap',
    category: 'Fashion', tags: ['accessories', 'cap'],
    price: 24.99, oldPrice: 34.99, rating: 4.4, reviewCount: 512, stock: 320,
    image: '../images/product-cap.svg', badge: 'sale',
    sizes: ['One size'], colors: ['Forest', 'Navy', 'Sand', 'Black'],
    description: 'Structured six-panel cotton twill cap with an adjustable brass buckle strap. Curved brim, embroidered logo.',
    specs: {
      'Material': '100% cotton twill',
      'Panels': '6, structured',
      'Closure': 'Adjustable brass strap',
      'Brim': 'Curved, pre-formed',
      'Care': 'Hand wash',
      'Warranty': '6 months',
    },
  },
  {
    id: 29, sku: 'FSH-029', name: 'Everyday Cotton T-shirt (5-pack)',
    category: 'Fashion', tags: ['basics', 'tshirt'],
    price: 45.00, oldPrice: 60.00, rating: 4.5, reviewCount: 903, stock: 480,
    image: '../images/product-jeans.svg', badge: 'hot',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Mixed'],
    description: 'Five heavyweight cotton crew tees in coordinated neutrals. Pre-shrunk, side-seamed for a clean fit.',
    specs: {
      'Material': '100% ring-spun cotton',
      'Weight': '220 gsm',
      'Fit': 'Regular, side-seamed',
      'Pack': '5 shirts',
      'Care': 'Machine wash',
      'Warranty': 'N/A',
    },
  },
  {
    id: 30, sku: 'FSH-030', name: 'Cashmere Turtleneck',
    category: 'Fashion', tags: ['knitwear', 'luxury'],
    price: 179.00, oldPrice: 229.00, rating: 4.8, reviewCount: 132, stock: 26,
    image: '../images/product-sweater.svg', badge: 'sale',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Camel', 'Black', 'Cream'],
    description: 'Grade-A Mongolian cashmere. Feather-light, ultra-warm, and unfussy. Perfect under a blazer or with jeans.',
    specs: {
      'Material': '100% cashmere (grade A)',
      'Ply': '2-ply',
      'Weight': '270 gsm',
      'Fit': 'Slim',
      'Care': 'Dry clean or hand wash',
      'Warranty': '1 year',
    },
  },
  {
    id: 31, sku: 'FSH-031', name: 'White Sneakers Court Low',
    category: 'Fashion', tags: ['footwear', 'sneakers'],
    price: 74.99, oldPrice: 99.99, rating: 4.5, reviewCount: 588, stock: 145,
    image: '../images/product-boots.svg', badge: null,
    sizes: ['6', '7', '8', '9', '10', '11'], colors: ['White', 'White/Navy', 'White/Green'],
    description: 'Minimal court sneakers with a supple leather upper, cushioned insole and a vulcanised rubber outsole. Goes with everything.',
    specs: {
      'Upper': 'Leather',
      'Insole': 'Memory foam',
      'Outsole': 'Vulcanised rubber',
      'Weight': '320 g / shoe',
      'Care': 'Wipe clean',
      'Warranty': '6 months',
    },
  },
  {
    id: 32, sku: 'FSH-032', name: 'Wide-brim Wool Fedora',
    category: 'Fashion', tags: ['accessories', 'hat'],
    price: 69.00, oldPrice: 89.00, rating: 4.6, reviewCount: 84, stock: 40,
    image: '../images/product-cap.svg', badge: null,
    sizes: ['S/M', 'L/XL'], colors: ['Camel', 'Charcoal', 'Black'],
    description: '100% wool felt fedora with a grosgrain band and a 7 cm brim. Water-repellent finish keeps its shape through the seasons.',
    specs: {
      'Material': '100% wool felt',
      'Brim': '7 cm',
      'Band': 'Grosgrain',
      'Finish': 'Water repellent',
      'Care': 'Brush, spot clean',
      'Warranty': '1 year',
    },
  },
  {
    id: 33, sku: 'FSH-033', name: 'Vintage Wash Denim Jacket',
    category: 'Fashion', tags: ['outerwear', 'denim'],
    price: 89.99, oldPrice: 119.99, rating: 4.4, reviewCount: 267, stock: 72,
    image: '../images/product-jeans.svg', badge: 'sale',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Light Wash', 'Dark Wash'],
    description: 'Rigid selvedge denim jacket with a stone-washed finish, chest flap pockets and button-cuff sleeves. Wears in beautifully.',
    specs: {
      'Material': '100% cotton selvedge denim',
      'Weight': '14 oz',
      'Closure': 'Button front',
      'Pockets': '4',
      'Care': 'Machine wash cold, inside out',
      'Warranty': '1 year',
    },
  },
  {
    id: 34, sku: 'FSH-034', name: 'Puffer Vest Recycled Down',
    category: 'Fashion', tags: ['outerwear', 'vest'],
    price: 129.00, oldPrice: 159.00, rating: 4.5, reviewCount: 145, stock: 36,
    image: '../images/product-sweater.svg', badge: 'new',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Olive', 'Navy', 'Black'],
    description: 'Featherweight puffer vest filled with 700-fill responsibly-sourced recycled down. Zip pockets, packs into its own bag.',
    specs: {
      'Shell': 'Ripstop nylon (recycled)',
      'Fill': '700-fill recycled down',
      'Weight': '310 g',
      'Packable': 'Yes, into own pocket',
      'Care': 'Machine wash gentle',
      'Warranty': '2 years',
    },
  },
  {
    id: 35, sku: 'FSH-035', name: 'Silk Twill Neck Scarf',
    category: 'Fashion', tags: ['accessories', 'silk'],
    price: 49.00, oldPrice: 69.00, rating: 4.6, reviewCount: 92, stock: 88,
    image: '../images/product-cap.svg', badge: null,
    sizes: ['70 cm square'], colors: ['Emerald', 'Rose', 'Cobalt', 'Ivory'],
    description: 'Hand-rolled 100% silk twill scarf, screen-printed in Como, Italy. A finishing touch for any outfit.',
    specs: {
      'Material': '100% silk twill',
      'Size': '70 cm x 70 cm',
      'Weight': '18 momme',
      'Print': 'Screen-printed in Como',
      'Care': 'Dry clean',
      'Warranty': '6 months',
    },
  },
  {
    id: 36, sku: 'FSH-036', name: 'Yoga Leggings High-rise',
    category: 'Fashion', tags: ['activewear', 'yoga'],
    price: 54.99, oldPrice: 79.99, rating: 4.7, reviewCount: 719, stock: 264,
    image: '../images/product-jeans.svg', badge: 'hot',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Black', 'Olive', 'Plum', 'Storm'],
    description: 'Buttery-soft four-way stretch high-rise leggings with a hidden waistband pocket. Squat-proof and sweat-wicking.',
    specs: {
      'Material': '78% nylon, 22% spandex',
      'Rise': 'High (26 cm)',
      'Inseam': '25" (regular)',
      'Features': 'Hidden waistband pocket',
      'Care': 'Machine wash cold',
      'Warranty': '1 year',
    },
  },

  /* -------- Home fillers (37-48) so category has 15 -------- */
  {
    id: 37, sku: 'HOM-037', name: 'AtmoFresh HEPA Air Purifier',
    category: 'Home', tags: ['appliance', 'wellness'],
    price: 249.00, oldPrice: 299.00, rating: 4.7, reviewCount: 421, stock: 44,
    image: '../images/product-air-purifier.svg', badge: 'sale',
    sizes: ['Room (60 sqm)', 'Large (100 sqm)'], colors: ['White', 'Graphite'],
    description: 'True-HEPA H13 filter captures 99.97% of particles down to 0.3 micron. Whisper-quiet at 24 dB in sleep mode, with live air-quality readouts.',
    specs: {
      'Coverage': 'Up to 60 sqm (Room), 100 sqm (Large)',
      'Filter': 'H13 True-HEPA + activated carbon',
      'Noise': '24 dB (sleep) to 52 dB (turbo)',
      'CADR': '400 m3/h',
      'Sensors': 'PM2.5, VOC, humidity',
      'Warranty': '2 years',
    },
  },
  {
    id: 38, sku: 'HOM-038', name: 'CleanBot X1 Robot Vacuum',
    category: 'Home', tags: ['appliance', 'cleaning'],
    price: 429.00, oldPrice: 549.00, rating: 4.6, reviewCount: 852, stock: 22,
    image: '../images/product-vacuum.svg', badge: 'hot',
    sizes: [], colors: ['Space Grey'],
    description: 'LiDAR-mapped robot vacuum with mopping combo, 5,200 Pa suction and auto-empty base. Sets no-go zones from the app.',
    specs: {
      'Suction': '5,200 Pa',
      'Mapping': 'LiDAR + AI obstacle recognition',
      'Battery': '5,200 mAh (180 min)',
      'Bin capacity': '400 ml (auto-empty 2.5 L)',
      'App': 'iOS + Android + Alexa/Google',
      'Warranty': '2 years',
    },
  },
  {
    id: 39, sku: 'HOM-039', name: 'ForgeIron 12" Skillet',
    category: 'Home', tags: ['kitchen', 'cookware'],
    price: 79.99, oldPrice: 99.99, rating: 4.8, reviewCount: 611, stock: 130,
    image: '../images/product-skillet.svg', badge: null,
    sizes: ['10 inch', '12 inch'], colors: ['Black'],
    description: 'Pre-seasoned cast iron skillet, oven-safe to 260 degC. Excellent heat retention for searing steaks, baking cornbread and everything in between.',
    specs: {
      'Diameter': '12 inch (30.5 cm)',
      'Weight': '3.2 kg',
      'Seasoning': 'Vegetable oil, factory pre-seasoned',
      'Oven safe': 'Up to 260 degC',
      'Induction': 'Yes',
      'Warranty': 'Lifetime',
    },
  },
  {
    id: 40, sku: 'HOM-040', name: 'Whirlwind 1500W Blender Pro',
    category: 'Home', tags: ['kitchen', 'appliance'],
    price: 189.00, oldPrice: 229.00, rating: 4.5, reviewCount: 297, stock: 48,
    image: '../images/product-blender.svg', badge: 'sale',
    sizes: ['1.5 L jar', '2.0 L jar'], colors: ['Red', 'Black'],
    description: '1,500 W motor and stainless steel 6-point blade rip through smoothies, soups and nut butters. 8 preset modes plus variable speed.',
    specs: {
      'Motor': '1,500 W, 32,000 rpm',
      'Jar': 'BPA-free tritan, 1.5 L',
      'Programs': '8 presets + pulse + variable',
      'Blade': '6-point stainless steel',
      'Noise': '85 dB max',
      'Warranty': '7 years motor',
    },
  },
  {
    id: 41, sku: 'HOM-041', name: 'CozyBlend Bedsheet Set 400TC',
    category: 'Home', tags: ['bedding'],
    price: 79.99, oldPrice: 109.00, rating: 4.5, reviewCount: 348, stock: 210,
    image: '../images/product-air-purifier.svg', badge: null,
    sizes: ['Queen', 'King', 'Super King'], colors: ['Ivory', 'Sage', 'Charcoal', 'Blush'],
    description: '400-thread-count sateen bedsheet set with deep-pocket fitted sheet, flat sheet and two pillowcases. OEKO-TEX certified cotton.',
    specs: {
      'Material': '100% long-staple cotton',
      'Weave': 'Sateen, 400 TC',
      'Set': 'Fitted + flat + 2 pillowcases',
      'Pocket depth': '40 cm',
      'Certification': 'OEKO-TEX Standard 100',
      'Warranty': '1 year',
    },
  },
  {
    id: 42, sku: 'HOM-042', name: 'Mistwood Aroma Diffuser',
    category: 'Home', tags: ['wellness', 'decor'],
    price: 44.99, oldPrice: 59.99, rating: 4.4, reviewCount: 176, stock: 132,
    image: '../images/product-air-purifier.svg', badge: 'sale',
    sizes: ['300 ml', '500 ml'], colors: ['Light Wood', 'Dark Wood'],
    description: 'Ultrasonic essential-oil diffuser with 7-colour ambient lighting and 3 mist modes. Whisper quiet, auto shut-off when empty.',
    specs: {
      'Capacity': '300 ml',
      'Runtime': 'Up to 10 h (intermittent)',
      'Modes': '3 mist + 7 light',
      'Coverage': 'Up to 25 sqm',
      'Noise': '<28 dB',
      'Warranty': '1 year',
    },
  },
  {
    id: 43, sku: 'HOM-043', name: 'Sunrise Wall Clock',
    category: 'Home', tags: ['decor'],
    price: 34.99, oldPrice: 49.99, rating: 4.3, reviewCount: 89, stock: 75,
    image: '../images/product-vacuum.svg', badge: null,
    sizes: ['30 cm', '40 cm'], colors: ['Walnut', 'White', 'Black'],
    description: 'Silent-sweep wall clock with a solid wood frame and clean matte dial. No ticking noise — ideal for bedrooms and offices.',
    specs: {
      'Diameter': '30 cm',
      'Movement': 'Silent quartz sweep',
      'Frame': 'Solid walnut',
      'Power': '1x AA battery',
      'Mount': 'Wall hook (incl.)',
      'Warranty': '1 year',
    },
  },
  {
    id: 44, sku: 'HOM-044', name: 'Egyptian Cotton Bath Towel Set',
    category: 'Home', tags: ['bath'],
    price: 59.99, oldPrice: 79.99, rating: 4.6, reviewCount: 421, stock: 168,
    image: '../images/product-air-purifier.svg', badge: 'hot',
    sizes: ['6-piece', '8-piece'], colors: ['White', 'Sand', 'Sage', 'Slate'],
    description: 'Plush 600 gsm Egyptian cotton towels. Absorbent, fluffy, and holds up to daily use without going scratchy.',
    specs: {
      'Material': '100% Egyptian cotton',
      'Weight': '600 gsm',
      'Set': '2 bath + 2 hand + 2 washcloths',
      'Weave': 'Zero-twist loop',
      'Care': 'Machine wash warm',
      'Warranty': '1 year',
    },
  },
  {
    id: 45, sku: 'HOM-045', name: 'HandThrown Ceramic Dinner Set (16pc)',
    category: 'Home', tags: ['kitchen', 'tableware'],
    price: 129.00, oldPrice: 169.00, rating: 4.7, reviewCount: 156, stock: 34,
    image: '../images/product-skillet.svg', badge: 'sale',
    sizes: ['Service for 4', 'Service for 6'], colors: ['Matte White', 'Speckled Sand'],
    description: 'Reactive-glaze stoneware dinner set: 4 dinner plates, 4 salad plates, 4 bowls and 4 mugs. Dishwasher and microwave safe.',
    specs: {
      'Pieces': '16 (service for 4)',
      'Material': 'Stoneware, reactive glaze',
      'Dishwasher': 'Yes',
      'Microwave': 'Yes',
      'Oven': 'Up to 220 degC',
      'Warranty': '1 year',
    },
  },
  {
    id: 46, sku: 'HOM-046', name: 'WeavRug 5x8 Handloom',
    category: 'Home', tags: ['decor', 'rugs'],
    price: 199.00, oldPrice: 279.00, rating: 4.5, reviewCount: 63, stock: 22,
    image: '../images/product-vacuum.svg', badge: 'new',
    sizes: ['5x8 ft', '8x10 ft'], colors: ['Ivory', 'Rust', 'Indigo', 'Charcoal'],
    description: 'Hand-loomed 100% wool area rug with a low-pile geometric pattern. Reversible construction extends its life.',
    specs: {
      'Material': '100% wool',
      'Pile': 'Low, 8 mm',
      'Backing': 'Cotton canvas',
      'Weave': 'Handloom (reversible)',
      'Care': 'Professional clean',
      'Warranty': '2 years',
    },
  },
  {
    id: 47, sku: 'HOM-047', name: 'StackBins Storage Set (6)',
    category: 'Home', tags: ['storage', 'organisation'],
    price: 49.99, oldPrice: 69.99, rating: 4.4, reviewCount: 214, stock: 190,
    image: '../images/product-blender.svg', badge: null,
    sizes: ['Small (6L)', 'Medium (12L)', 'Large (25L)'], colors: ['Clear', 'Slate'],
    description: 'Stackable, snap-lid storage bins that lock together for closets, garages and pantries. Ventilated lids for breathable storage.',
    specs: {
      'Set': '6 bins',
      'Material': 'Recyclable PP',
      'Lid': 'Snap-lock, ventilated',
      'Stackable': 'Yes (interlocking)',
      'Load rating': '12 kg per bin',
      'Warranty': '5 years',
    },
  },
  {
    id: 48, sku: 'HOM-048', name: 'PrecisionKitchen Digital Scale',
    category: 'Home', tags: ['kitchen'],
    price: 24.99, oldPrice: 34.99, rating: 4.6, reviewCount: 508, stock: 260,
    image: '../images/product-skillet.svg', badge: 'sale',
    sizes: [], colors: ['Stainless', 'Matte Black'],
    description: 'Slim digital kitchen scale, accurate to 1 g up to 5 kg. Tare button, unit toggle, auto shut-off and a backlit LCD.',
    specs: {
      'Capacity': '5 kg (5,000 g)',
      'Accuracy': '+/- 1 g',
      'Units': 'g, oz, lb, ml, fl-oz',
      'Platform': 'Tempered glass',
      'Power': '2x AAA (incl.)',
      'Warranty': '2 years',
    },
  },

  /* -------- Books fillers (49-60) so category has 15 -------- */
  {
    id: 49, sku: 'BOK-049', name: 'Atomic Habits',
    category: 'Books', tags: ['self-help', 'productivity'],
    price: 18.99, oldPrice: 26.99, rating: 4.8, reviewCount: 12045, stock: 500,
    image: '../images/product-book-yellow.svg', badge: 'hot',
    sizes: ['Paperback', 'Hardcover', 'eBook', 'Audiobook'], colors: [],
    description: 'A proven framework for building good habits and breaking bad ones. Tiny changes, remarkable results — millions of copies sold worldwide.',
    specs: {
      'Author': 'James Clear',
      'Pages': '320',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': 'International',
      'ISBN': '978-1-2345-7000-2',
    },
  },
  {
    id: 50, sku: 'BOK-050', name: 'The Great Gatsby (Classic Edition)',
    category: 'Books', tags: ['fiction', 'classic'],
    price: 12.99, oldPrice: 16.99, rating: 4.7, reviewCount: 6321, stock: 420,
    image: '../images/product-book-blue.svg', badge: 'sale',
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'F. Scott Fitzgerald’s Jazz Age masterpiece. A cloth-bound classic edition with an introduction by a leading literary historian.',
    specs: {
      'Author': 'F. Scott Fitzgerald',
      'Pages': '218',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': 'Cloth-bound classic',
      'ISBN': '978-1-2345-7001-9',
    },
  },
  {
    id: 51, sku: 'BOK-051', name: 'Sapiens: A Brief History of Humankind',
    category: 'Books', tags: ['non-fiction', 'history'],
    price: 22.99, oldPrice: 29.99, rating: 4.6, reviewCount: 8974, stock: 305,
    image: '../images/product-book-yellow.svg', badge: null,
    sizes: ['Paperback', 'Hardcover', 'eBook', 'Audiobook'], colors: [],
    description: 'From the Stone Age to the Silicon Valley — Yuval Noah Harari traces the entire arc of human history in a sweeping, provocative narrative.',
    specs: {
      'Author': 'Yuval Noah Harari',
      'Pages': '464',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '2nd',
      'ISBN': '978-1-2345-7002-6',
    },
  },
  {
    id: 52, sku: 'BOK-052', name: 'Zero to One',
    category: 'Books', tags: ['business', 'startup'],
    price: 19.99, oldPrice: 27.00, rating: 4.5, reviewCount: 4210, stock: 220,
    image: '../images/product-book-red.svg', badge: 'sale',
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'Peter Thiel’s notes on startups, or how to build the future. A concise, contrarian guide for anyone attempting to build something new.',
    specs: {
      'Author': 'Peter Thiel with Blake Masters',
      'Pages': '224',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '1st',
      'ISBN': '978-1-2345-7003-3',
    },
  },
  {
    id: 53, sku: 'BOK-053', name: 'Clean Code',
    category: 'Books', tags: ['programming', 'craft'],
    price: 34.99, oldPrice: 44.99, rating: 4.7, reviewCount: 5104, stock: 180,
    image: '../images/product-book-green.svg', badge: 'hot',
    sizes: ['Paperback', 'eBook'], colors: [],
    description: 'A handbook of agile software craftsmanship. Learn the principles, patterns and heuristics that separate readable software from a maintenance nightmare.',
    specs: {
      'Author': 'Robert C. Martin',
      'Pages': '464',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '1st',
      'ISBN': '978-1-2345-7004-0',
    },
  },
  {
    id: 54, sku: 'BOK-054', name: 'Deep Work',
    category: 'Books', tags: ['self-help', 'productivity'],
    price: 17.99, oldPrice: 24.99, rating: 4.6, reviewCount: 3892, stock: 260,
    image: '../images/product-book-yellow.svg', badge: null,
    sizes: ['Paperback', 'Hardcover', 'eBook', 'Audiobook'], colors: [],
    description: 'Cal Newport’s rules for focused success in a distracted world. Reclaim your attention and produce work that matters.',
    specs: {
      'Author': 'Cal Newport',
      'Pages': '304',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '1st',
      'ISBN': '978-1-2345-7005-7',
    },
  },
  {
    id: 55, sku: 'BOK-055', name: 'Educated: A Memoir',
    category: 'Books', tags: ['non-fiction', 'memoir'],
    price: 16.99, oldPrice: 22.99, rating: 4.7, reviewCount: 6543, stock: 190,
    image: '../images/product-book-red.svg', badge: null,
    sizes: ['Paperback', 'Hardcover', 'eBook', 'Audiobook'], colors: [],
    description: 'Tara Westover’s remarkable journey from a survivalist family in the Idaho mountains to a PhD at Cambridge. An anthem to learning.',
    specs: {
      'Author': 'Tara Westover',
      'Pages': '352',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '1st',
      'ISBN': '978-1-2345-7006-4',
    },
  },
  {
    id: 56, sku: 'BOK-056', name: 'The Pragmatic Programmer (20th Anniv.)',
    category: 'Books', tags: ['programming', 'craft'],
    price: 39.99, oldPrice: 49.99, rating: 4.8, reviewCount: 3287, stock: 145,
    image: '../images/product-book-green.svg', badge: 'sale',
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'Your journey to mastery — a modern update of the classic guide that helped a generation of developers ship better software.',
    specs: {
      'Author': 'David Thomas, Andrew Hunt',
      'Pages': '352',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '20th anniversary',
      'ISBN': '978-1-2345-7007-1',
    },
  },
  {
    id: 57, sku: 'BOK-057', name: 'Cosmos',
    category: 'Books', tags: ['non-fiction', 'science'],
    price: 21.99, oldPrice: 29.99, rating: 4.8, reviewCount: 4126, stock: 132,
    image: '../images/product-book-blue.svg', badge: null,
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'Carl Sagan’s lyrical tour of the universe — from ancient astronomy to modern astrophysics. Illustrated throughout.',
    specs: {
      'Author': 'Carl Sagan',
      'Pages': '396',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': 'Illustrated',
      'ISBN': '978-1-2345-7008-8',
    },
  },
  {
    id: 58, sku: 'BOK-058', name: 'Grit: The Power of Passion and Perseverance',
    category: 'Books', tags: ['self-help', 'psychology'],
    price: 16.49, oldPrice: 22.99, rating: 4.5, reviewCount: 2941, stock: 210,
    image: '../images/product-book-red.svg', badge: 'sale',
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'Psychologist Angela Duckworth on why talent is over-rated — and how grit, a blend of passion and perseverance, is the true predictor of achievement.',
    specs: {
      'Author': 'Angela Duckworth',
      'Pages': '352',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '1st',
      'ISBN': '978-1-2345-7009-5',
    },
  },
  {
    id: 59, sku: 'BOK-059', name: 'The Alchemist',
    category: 'Books', tags: ['fiction', 'philosophical'],
    price: 14.99, oldPrice: 19.99, rating: 4.7, reviewCount: 9812, stock: 480,
    image: '../images/product-book-yellow.svg', badge: 'hot',
    sizes: ['Paperback', 'Hardcover', 'eBook', 'Audiobook'], colors: [],
    description: 'Paulo Coelho’s modern parable of dreams, destiny and the courage to follow one’s heart. Translated into 80+ languages.',
    specs: {
      'Author': 'Paulo Coelho',
      'Pages': '208',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '25th anniversary',
      'ISBN': '978-1-2345-7010-1',
    },
  },
  {
    id: 60, sku: 'BOK-060', name: 'Steal Like an Artist',
    category: 'Books', tags: ['creativity', 'design'],
    price: 13.99, oldPrice: 18.99, rating: 4.6, reviewCount: 3542, stock: 340,
    image: '../images/product-book-blue.svg', badge: 'new',
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'Austin Kleon’s slim, generous handbook for creative work. 10 things nobody told you about being creative — with illustrations you will want to frame.',
    specs: {
      'Author': 'Austin Kleon',
      'Pages': '160',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '10th anniversary',
      'ISBN': '978-1-2345-7011-8',
    },
  },

  /* ============================================================
     WAVE 2 fillers (61-85) — every category ends up in [15, 25]
     Electronics: 18, Fashion: 22, Home: 20, Books: 25
     ============================================================ */

  /* -------- Electronics (61-63) -------- */
  {
    id: 61, sku: 'ELE-061', name: 'HoloLens Air VR Headset',
    category: 'Electronics', tags: ['vr', 'gaming', 'immersive'],
    price: 599.00, oldPrice: 699.00, rating: 4.4, reviewCount: 189, stock: 24,
    image: '../images/product-vr.svg', badge: 'new',
    sizes: [], colors: ['Graphite'],
    description: 'Lightweight standalone VR/AR headset with 4K per-eye micro-OLED panels, inside-out tracking and hand + eye gestures. No PC required — pancake optics keep the whole rig under 400 g.',
    specs: {
      'Display': '4K per eye micro-OLED, 120 Hz',
      'Optics': 'Pancake, 110-degree FoV',
      'Tracking': 'Inside-out + eye + hand',
      'Chipset': 'Snapdragon XR3+',
      'Battery': '3 h (hot-swappable pack)',
      'Weight': '395 g',
      'Warranty': '1 year',
    },
  },
  {
    id: 62, sku: 'ELE-062', name: 'Kindle Scribe 2 (16 GB)',
    category: 'Electronics', tags: ['e-reader', 'reading', 'notes'],
    price: 339.00, oldPrice: 379.00, rating: 4.5, reviewCount: 421, stock: 66,
    image: '../images/product-ipad.svg', badge: 'sale',
    sizes: ['16 GB', '32 GB', '64 GB'], colors: ['Tungsten', 'Metallic Jade'],
    description: 'A 10.2-inch 300 ppi Paperwhite display you can read on for weeks and write on with the included Premium Pen. Front-lit, warm-light, glare-free.',
    specs: {
      'Display': '10.2" 300 ppi Paperwhite',
      'Pen': 'Premium Pen (included)',
      'Battery': 'Up to 12 weeks reading',
      'Storage': '16 GB (up to 64 GB)',
      'Connectivity': 'Wi-Fi 6, USB-C',
      'Waterproof': 'IPX8',
      'Warranty': '1 year',
    },
  },
  {
    id: 63, sku: 'ELE-063', name: 'Sony WH-1000XM6 Wireless Headphones',
    category: 'Electronics', tags: ['audio', 'wireless', 'anc'],
    price: 429.00, oldPrice: 499.00, rating: 4.8, reviewCount: 934, stock: 52,
    image: '../images/product-headphones.svg', badge: 'hot',
    sizes: [], colors: ['Black', 'Silver', 'Midnight Blue'],
    description: 'The industry benchmark for noise-cancelling headphones. Dual QN2 processors, 12 mics for adaptive ANC, and up to 40 hours of listening.',
    specs: {
      'Type': 'Over-ear wireless',
      'ANC': 'Adaptive, dual QN2 processors',
      'Battery': '40 h (3 min quick-charge = 3 h)',
      'Codec': 'LDAC, aptX Adaptive, AAC',
      'Bluetooth': '5.4 multipoint',
      'Weight': '250 g',
      'Warranty': '2 years',
    },
  },

  /* -------- Fashion (64-70) -------- */
  {
    id: 64, sku: 'FSH-064', name: 'Wool Overcoat Camel',
    category: 'Fashion', tags: ['outerwear', 'wool', 'formal'],
    price: 289.00, oldPrice: 359.00, rating: 4.7, reviewCount: 152, stock: 24,
    image: '../images/product-leather-jacket.svg', badge: 'new',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Camel', 'Charcoal', 'Navy'],
    description: 'Single-breasted knee-length overcoat in a soft Italian wool-cashmere blend. Notch lapel, welt pockets, and a satin cupro lining.',
    specs: {
      'Material': '85% wool, 15% cashmere',
      'Weight': '620 gsm',
      'Lining': 'Cupro satin',
      'Buttons': 'Horn',
      'Care': 'Dry clean only',
      'Warranty': '1 year',
    },
  },
  {
    id: 65, sku: 'FSH-065', name: 'Two-ply Cotton Dress Shirt',
    category: 'Fashion', tags: ['formal', 'shirt'],
    price: 79.00, oldPrice: 99.00, rating: 4.6, reviewCount: 421, stock: 168,
    image: '../images/product-shirt.svg', badge: 'sale',
    sizes: ['14.5"', '15"', '15.5"', '16"', '16.5"', '17"'],
    colors: ['White', 'Sky Blue', 'Pink', 'Charcoal'],
    description: 'Two-ply 100/2 poplin dress shirt with mother-of-pearl buttons and a classic point collar. Wrinkle-resistant finish.',
    specs: {
      'Material': '100% two-ply cotton (100/2)',
      'Weave': 'Poplin',
      'Collar': 'Point (semi-spread)',
      'Cuffs': 'Barrel, 2-button',
      'Care': 'Machine wash cold',
      'Warranty': '6 months',
    },
  },
  {
    id: 66, sku: 'FSH-066', name: 'Stretch Chino Trousers',
    category: 'Fashion', tags: ['bottoms', 'chino'],
    price: 54.99, oldPrice: 79.99, rating: 4.5, reviewCount: 519, stock: 240,
    image: '../images/product-jeans.svg', badge: null,
    sizes: ['28', '30', '32', '34', '36', '38'], colors: ['Khaki', 'Stone', 'Olive', 'Navy'],
    description: 'All-day comfort stretch chinos with a slim tapered leg. Structured enough for the office, soft enough for a Sunday brunch.',
    specs: {
      'Material': '97% cotton, 3% elastane',
      'Rise': 'Mid',
      'Fit': 'Slim tapered',
      'Pockets': '4 (2 side, 2 back with button)',
      'Care': 'Machine wash cool',
      'Warranty': '6 months',
    },
  },
  {
    id: 67, sku: 'FSH-067', name: 'Full-grain Leather Belt',
    category: 'Fashion', tags: ['accessories', 'leather'],
    price: 49.00, oldPrice: 69.00, rating: 4.7, reviewCount: 302, stock: 220,
    image: '../images/product-boots.svg', badge: 'hot',
    sizes: ['30', '32', '34', '36', '38', '40'], colors: ['Chocolate', 'Black', 'Tan'],
    description: '3.5 mm thick vegetable-tanned full-grain leather belt with a solid brass buckle. Ages beautifully.',
    specs: {
      'Material': 'Full-grain vegetable-tanned leather',
      'Thickness': '3.5 mm',
      'Width': '32 mm',
      'Buckle': 'Solid brass',
      'Care': 'Wax polish quarterly',
      'Warranty': '1 year',
    },
  },
  {
    id: 68, sku: 'FSH-068', name: 'Woven Silk Necktie',
    category: 'Fashion', tags: ['formal', 'accessories'],
    price: 39.00, oldPrice: 55.00, rating: 4.5, reviewCount: 128, stock: 140,
    image: '../images/product-cap.svg', badge: null,
    sizes: ['Standard (147 x 8 cm)'], colors: ['Burgundy', 'Navy', 'Emerald', 'Charcoal'],
    description: 'Hand-tipped woven-silk necktie with a classic 8 cm blade. Made in Italy from 60 gm silk.',
    specs: {
      'Material': '100% silk (60 gm)',
      'Construction': 'Hand-tipped, three-fold',
      'Length': '147 cm',
      'Blade width': '8 cm',
      'Care': 'Dry clean',
      'Warranty': '6 months',
    },
  },
  {
    id: 69, sku: 'FSH-069', name: 'Arctic Down Parka',
    category: 'Fashion', tags: ['outerwear', 'winter'],
    price: 349.00, oldPrice: 449.00, rating: 4.8, reviewCount: 231, stock: 34,
    image: '../images/product-sweater.svg', badge: 'sale',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'], colors: ['Black', 'Navy', 'Olive'],
    description: 'Below-zero rated parka with 800-fill responsibly-sourced down, coyote-free faux fur hood trim, and taped critical seams.',
    specs: {
      'Shell': '2L ripstop nylon with DWR',
      'Fill': '800-fill responsible down',
      'Rating': 'Comfort to -30 degC',
      'Hood': 'Adjustable, faux fur trim',
      'Pockets': '6 (2 handwarmer, 4 utility)',
      'Warranty': '2 years',
    },
  },
  {
    id: 70, sku: 'FSH-070', name: 'Performance Training Shorts',
    category: 'Fashion', tags: ['activewear', 'shorts'],
    price: 34.99, oldPrice: 49.99, rating: 4.6, reviewCount: 612, stock: 380,
    image: '../images/product-jeans.svg', badge: 'hot',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Black', 'Charcoal', 'Navy', 'Olive'],
    description: 'Featherweight 4-way stretch training shorts with a hidden zip pocket, mesh side panels and a soft elasticated waistband.',
    specs: {
      'Material': '90% polyester, 10% spandex',
      'Weight': '110 gsm',
      'Inseam': '7 inch',
      'Features': 'Hidden zip pocket, mesh panels',
      'Care': 'Machine wash cold',
      'Warranty': '1 year',
    },
  },

  /* -------- Home (71-75) -------- */
  {
    id: 71, sku: 'HOM-071', name: 'BrewMaster Espresso Machine',
    category: 'Home', tags: ['kitchen', 'coffee', 'appliance'],
    price: 549.00, oldPrice: 649.00, rating: 4.6, reviewCount: 289, stock: 26,
    image: '../images/product-coffee-maker.svg', badge: 'sale',
    sizes: [], colors: ['Brushed Steel', 'Matte Black'],
    description: 'Single-boiler espresso machine with a professional 58 mm portafilter, PID temperature control and an integrated conical burr grinder.',
    specs: {
      'Pressure': '15 bar (pre-infusion)',
      'Boiler': 'Single, PID controlled',
      'Portafilter': '58 mm commercial',
      'Grinder': 'Integrated conical burr',
      'Water tank': '2.5 L',
      'Warranty': '2 years',
    },
  },
  {
    id: 72, sku: 'HOM-072', name: 'CozyCotton Weighted Blanket',
    category: 'Home', tags: ['bedding', 'wellness'],
    price: 129.00, oldPrice: 169.00, rating: 4.7, reviewCount: 812, stock: 84,
    image: '../images/product-air-purifier.svg', badge: 'hot',
    sizes: ['7 kg (Queen)', '9 kg (King)', '11 kg (Super King)'],
    colors: ['Grey', 'Navy', 'Sand'],
    description: '100% cotton weighted blanket with glass-bead fill for gentle, evenly distributed pressure. Includes a soft minky-plush removable cover.',
    specs: {
      'Outer': '100% cotton',
      'Fill': 'Glass beads (non-toxic)',
      'Cover': 'Minky plush, removable',
      'Weights': '7 / 9 / 11 kg',
      'Care': 'Cover machine wash',
      'Warranty': '3 years',
    },
  },
  {
    id: 73, sku: 'HOM-073', name: 'Beam LED Floor Lamp',
    category: 'Home', tags: ['lighting', 'decor'],
    price: 89.99, oldPrice: 119.99, rating: 4.4, reviewCount: 154, stock: 46,
    image: '../images/product-table-lamp.svg', badge: null,
    sizes: ['1.6 m'], colors: ['Matte Black', 'Brass', 'White'],
    description: 'Tall arc floor lamp with an adjustable head, dimmer, and a warm 3000 K LED. Weighted marble base keeps it stable.',
    specs: {
      'Bulb': '15 W LED (3000 K)',
      'Dimming': 'Rotary, 0-100%',
      'Height': '1.6 m',
      'Base': 'Marble',
      'Rated life': '25,000 h',
      'Warranty': '2 years',
    },
  },
  {
    id: 74, sku: 'HOM-074', name: 'Handcrafted Ceramic Vase Set (3)',
    category: 'Home', tags: ['decor'],
    price: 79.99, oldPrice: 109.00, rating: 4.5, reviewCount: 96, stock: 62,
    image: '../images/product-vase.svg', badge: 'new',
    sizes: ['Small (15 cm)', 'Medium (22 cm)', 'Large (30 cm)'],
    colors: ['Blush', 'Sand', 'Olive'],
    description: 'Set of three hand-thrown stoneware vases in coordinated matte glazes. Sculptural on their own, stunning as a trio.',
    specs: {
      'Pieces': '3',
      'Material': 'Stoneware',
      'Finish': 'Matte glaze',
      'Watertight': 'Yes',
      'Care': 'Wipe clean',
      'Warranty': '6 months',
    },
  },
  {
    id: 75, sku: 'HOM-075', name: 'Bamboo Cutting Board Set',
    category: 'Home', tags: ['kitchen'],
    price: 29.99, oldPrice: 44.99, rating: 4.6, reviewCount: 421, stock: 320,
    image: '../images/product-knives-set.svg', badge: 'sale',
    sizes: ['3-piece', '5-piece'], colors: ['Natural Bamboo'],
    description: 'Antibacterial, knife-friendly bamboo cutting boards with juice grooves and integrated handles. Comes in three sizes.',
    specs: {
      'Material': 'FSC-certified bamboo',
      'Pieces': '3 (S / M / L)',
      'Juice groove': 'Yes',
      'Care': 'Hand wash, oil monthly',
      'Thickness': '18 mm',
      'Warranty': '1 year',
    },
  },

  /* -------- Books (76-85) -------- */
  {
    id: 76, sku: 'BOK-076', name: 'The Hobbit',
    category: 'Books', tags: ['fiction', 'fantasy'],
    price: 15.99, oldPrice: 21.99, rating: 4.9, reviewCount: 14203, stock: 520,
    image: '../images/product-book-green.svg', badge: 'hot',
    sizes: ['Paperback', 'Hardcover', 'eBook', 'Audiobook'], colors: [],
    description: 'J.R.R. Tolkien’s beloved adventure. Follow Bilbo Baggins from the Shire to the Lonely Mountain in this illustrated 75th-anniversary edition.',
    specs: {
      'Author': 'J.R.R. Tolkien',
      'Pages': '310',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '75th anniversary',
      'ISBN': '978-1-2345-7012-5',
    },
  },
  {
    id: 77, sku: 'BOK-077', name: 'Rich Dad Poor Dad',
    category: 'Books', tags: ['business', 'personal-finance'],
    price: 15.99, oldPrice: 21.99, rating: 4.5, reviewCount: 9876, stock: 420,
    image: '../images/product-book-yellow.svg', badge: null,
    sizes: ['Paperback', 'eBook', 'Audiobook'], colors: [],
    description: 'Robert Kiyosaki’s classic on money, mindset and financial literacy. What the rich teach their kids about money that the poor do not.',
    specs: {
      'Author': 'Robert T. Kiyosaki',
      'Pages': '336',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '20th anniversary',
      'ISBN': '978-1-2345-7013-2',
    },
  },
  {
    id: 78, sku: 'BOK-078', name: 'Thinking, Fast and Slow',
    category: 'Books', tags: ['non-fiction', 'psychology'],
    price: 19.99, oldPrice: 27.99, rating: 4.6, reviewCount: 7423, stock: 260,
    image: '../images/product-book-blue.svg', badge: 'sale',
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'Nobel laureate Daniel Kahneman unpacks the two systems that drive the way we think — fast and intuitive, slow and deliberate.',
    specs: {
      'Author': 'Daniel Kahneman',
      'Pages': '499',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '1st',
      'ISBN': '978-1-2345-7014-9',
    },
  },
  {
    id: 79, sku: 'BOK-079', name: 'To Kill a Mockingbird',
    category: 'Books', tags: ['fiction', 'classic'],
    price: 13.99, oldPrice: 18.99, rating: 4.8, reviewCount: 12045, stock: 340,
    image: '../images/product-book-red.svg', badge: null,
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'Harper Lee’s Pulitzer Prize-winning novel of injustice and moral courage in a small Southern town — as urgent today as ever.',
    specs: {
      'Author': 'Harper Lee',
      'Pages': '336',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '60th anniversary',
      'ISBN': '978-1-2345-7015-6',
    },
  },
  {
    id: 80, sku: 'BOK-080', name: "Man's Search for Meaning",
    category: 'Books', tags: ['memoir', 'philosophy'],
    price: 14.49, oldPrice: 19.99, rating: 4.8, reviewCount: 8934, stock: 290,
    image: '../images/product-book-red.svg', badge: 'hot',
    sizes: ['Paperback', 'Hardcover', 'eBook', 'Audiobook'], colors: [],
    description: 'Viktor Frankl’s Holocaust-survivor memoir and the foundational text of logotherapy — one of the most influential books of the 20th century.',
    specs: {
      'Author': 'Viktor E. Frankl',
      'Pages': '200',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': 'Revised',
      'ISBN': '978-1-2345-7016-3',
    },
  },
  {
    id: 81, sku: 'BOK-081', name: 'Meditations',
    category: 'Books', tags: ['philosophy', 'classic'],
    price: 11.99, oldPrice: 16.99, rating: 4.7, reviewCount: 5602, stock: 380,
    image: '../images/product-book-green.svg', badge: null,
    sizes: ['Paperback', 'Hardcover', 'eBook', 'Audiobook'], colors: [],
    description: 'The private notebook of Roman emperor Marcus Aurelius — an enduring Stoic guide to living with clarity, courage and equanimity.',
    specs: {
      'Author': 'Marcus Aurelius',
      'Translator': 'Gregory Hays',
      'Pages': '304',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'ISBN': '978-1-2345-7017-0',
    },
  },
  {
    id: 82, sku: 'BOK-082', name: 'The Lean Startup',
    category: 'Books', tags: ['business', 'startup'],
    price: 18.99, oldPrice: 25.99, rating: 4.5, reviewCount: 4123, stock: 220,
    image: '../images/product-book-yellow.svg', badge: 'sale',
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'Eric Ries on how today’s entrepreneurs use continuous innovation to create radically successful businesses. Build-measure-learn, made practical.',
    specs: {
      'Author': 'Eric Ries',
      'Pages': '336',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '1st',
      'ISBN': '978-1-2345-7018-7',
    },
  },
  {
    id: 83, sku: 'BOK-083', name: 'Refactoring (2nd Edition)',
    category: 'Books', tags: ['programming', 'craft'],
    price: 42.99, oldPrice: 54.99, rating: 4.8, reviewCount: 3210, stock: 150,
    image: '../images/product-book-green.svg', badge: 'hot',
    sizes: ['Paperback', 'eBook'], colors: [],
    description: 'Martin Fowler’s definitive catalogue of code-smells and refactorings — updated with modern JavaScript examples in the second edition.',
    specs: {
      'Author': 'Martin Fowler',
      'Pages': '448',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '2nd',
      'ISBN': '978-1-2345-7019-4',
    },
  },
  {
    id: 84, sku: 'BOK-084', name: 'Homo Deus: A Brief History of Tomorrow',
    category: 'Books', tags: ['non-fiction', 'future'],
    price: 21.99, oldPrice: 28.99, rating: 4.5, reviewCount: 4890, stock: 210,
    image: '../images/product-book-blue.svg', badge: null,
    sizes: ['Paperback', 'Hardcover', 'eBook'], colors: [],
    description: 'Harari looks ahead: as we solve hunger, plague and war, what will we do next? A provocative meditation on where humanity might be heading.',
    specs: {
      'Author': 'Yuval Noah Harari',
      'Pages': '464',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '1st',
      'ISBN': '978-1-2345-7020-0',
    },
  },
  {
    id: 85, sku: 'BOK-085', name: 'Ikigai',
    category: 'Books', tags: ['self-help', 'lifestyle'],
    price: 13.49, oldPrice: 18.99, rating: 4.6, reviewCount: 6712, stock: 400,
    image: '../images/product-book-yellow.svg', badge: 'sale',
    sizes: ['Paperback', 'Hardcover', 'eBook', 'Audiobook'], colors: [],
    description: 'The Japanese secret to a long and happy life. Practical wisdom drawn from Okinawa, where more centenarians live per capita than anywhere else on Earth.',
    specs: {
      'Author': 'Hector Garcia, Francesc Miralles',
      'Pages': '208',
      'Publisher': 'ShopLane Press',
      'Language': 'English',
      'Edition': '1st',
      'ISBN': '978-1-2345-7021-7',
    },
  },

  /* ============================================================
     MEDICAL vertical (86-100) — instruments for home & clinic use
     Diagnostic (5) + Monitoring (5) + Aid & Mobility (5) = 15
     ============================================================ */
  {
    id: 86, sku: 'MED-086', name: 'CardioPro Cardiology Stethoscope',
    category: 'Medical', tags: ['diagnostic', 'cardio'], subCategory: 'Diagnostic',
    price: 189.00, oldPrice: 239.00, rating: 4.8, reviewCount: 421, stock: 42,
    image: '../images/product-stethoscope.svg', badge: 'hot',
    sizes: [], colors: ['Navy', 'Black', 'Burgundy'],
    description: 'Dual-lumen cardiology stethoscope with a hand-polished stainless chest piece. Ideal for auscultation of both bell and diaphragm frequencies.',
    specs: { 'Type': 'Cardiology dual-head', 'Chest piece': 'Stainless steel', 'Tubing': 'Latex-free PVC', 'Length': '69 cm', 'Warranty': '5 years' },
  },
  {
    id: 87, sku: 'MED-087', name: 'Otoscope + Ophthalmoscope Set',
    category: 'Medical', tags: ['diagnostic', 'ent'], subCategory: 'Diagnostic',
    price: 249.00, oldPrice: 299.00, rating: 4.6, reviewCount: 132, stock: 22,
    image: '../images/product-stethoscope.svg', badge: 'sale',
    sizes: [], colors: ['Chrome'],
    description: 'Fiber-optic otoscope and ophthalmoscope diagnostic set with rechargeable handle and hard carry case. Xenon-halogen illumination.',
    specs: { 'Illumination': 'Fiber-optic xenon', 'Battery': 'Li-ion, USB-C charge', 'Includes': 'Ear specula 5 sizes', 'Warranty': '3 years' },
  },
  {
    id: 88, sku: 'MED-088', name: 'Reflex Hammer (Buck Model)',
    category: 'Medical', tags: ['diagnostic', 'neuro'], subCategory: 'Diagnostic',
    price: 19.99, oldPrice: 29.99, rating: 4.5, reviewCount: 214, stock: 180,
    image: '../images/product-stethoscope.svg', badge: null,
    sizes: [], colors: ['Chrome/Red'],
    description: 'Buck-style reflex hammer with a soft rubber head and chrome-plated handle. Tests deep tendon reflexes reliably.',
    specs: { 'Head': 'Soft rubber', 'Handle': 'Chrome-plated', 'Length': '19 cm', 'Weight': '95 g', 'Warranty': '1 year' },
  },
  {
    id: 89, sku: 'MED-089', name: 'Diagnostic Penlight (5-pack)',
    category: 'Medical', tags: ['diagnostic', 'pen-torch'], subCategory: 'Diagnostic',
    price: 14.99, oldPrice: 24.99, rating: 4.4, reviewCount: 302, stock: 320,
    image: '../images/product-stethoscope.svg', badge: 'sale',
    sizes: [], colors: ['White'],
    description: 'Pack of 5 pupil-gauge diagnostic penlights. Cool white LED, replaceable batteries, integrated pocket clip.',
    specs: { 'Beam': 'Cool white LED', 'Battery': '2x AAA (incl.)', 'Length': '13 cm', 'Pack': '5 units', 'Warranty': '6 months' },
  },
  {
    id: 90, sku: 'MED-090', name: 'Tuning Fork Set (C128, C512)',
    category: 'Medical', tags: ['diagnostic', 'neuro'], subCategory: 'Diagnostic',
    price: 39.99, oldPrice: 54.99, rating: 4.6, reviewCount: 96, stock: 88,
    image: '../images/product-stethoscope.svg', badge: null,
    sizes: [], colors: ['Aluminium'],
    description: 'Precision aluminium alloy tuning forks (128 Hz + 512 Hz) with a felt-lined presentation case. For Rinne, Weber and vibration-sense testing.',
    specs: { 'Frequencies': '128 Hz + 512 Hz', 'Material': 'Aluminium alloy', 'Case': 'Felt lined', 'Warranty': '1 year' },
  },

  {
    id: 91, sku: 'MED-091', name: 'HomePulse Digital BP Monitor',
    category: 'Medical', tags: ['monitoring', 'bp'], subCategory: 'Monitoring',
    price: 89.00, oldPrice: 119.00, rating: 4.7, reviewCount: 812, stock: 132,
    image: '../images/product-bp-monitor.svg', badge: 'hot',
    sizes: ['Standard cuff (22-32 cm)', 'Large cuff (32-42 cm)'], colors: ['White'],
    description: 'Clinically validated upper-arm blood-pressure monitor with irregular-heartbeat detection, 90-reading memory for 2 users, and one-touch operation.',
    specs: { 'Method': 'Oscillometric', 'Memory': '2 x 90 readings', 'Display': 'Backlit LCD', 'Cuff': '22-32 cm (large avail.)', 'Warranty': '5 years' },
  },
  {
    id: 92, sku: 'MED-092', name: 'PulseOx Fingertip Pulse Oximeter',
    category: 'Medical', tags: ['monitoring', 'spo2'], subCategory: 'Monitoring',
    price: 34.99, oldPrice: 49.99, rating: 4.6, reviewCount: 921, stock: 260,
    image: '../images/product-bp-monitor.svg', badge: 'sale',
    sizes: [], colors: ['White', 'Blue'],
    description: 'Fingertip pulse oximeter with OLED display and plethysmograph waveform. Accurate SpO2 within ±2%.',
    specs: { 'SpO2 range': '35-100%', 'Accuracy': '+/- 2%', 'Display': 'OLED 4-way', 'Battery': '2x AAA', 'Warranty': '2 years' },
  },
  {
    id: 93, sku: 'MED-093', name: 'ThermScan Infrared Thermometer',
    category: 'Medical', tags: ['monitoring', 'temperature'], subCategory: 'Monitoring',
    price: 44.99, oldPrice: 59.99, rating: 4.5, reviewCount: 512, stock: 210,
    image: '../images/product-bp-monitor.svg', badge: null,
    sizes: [], colors: ['White'],
    description: 'Non-contact infrared forehead thermometer. 1-second reading, fever alarm, 32-reading memory. Certified medical accuracy.',
    specs: { 'Method': 'Infrared forehead', 'Response': '1 second', 'Accuracy': '+/- 0.2 degC', 'Memory': '32 readings', 'Warranty': '2 years' },
  },
  {
    id: 94, sku: 'MED-094', name: 'GlucoCare Glucometer Starter Kit',
    category: 'Medical', tags: ['monitoring', 'diabetes'], subCategory: 'Monitoring',
    price: 39.99, oldPrice: 54.99, rating: 4.5, reviewCount: 623, stock: 168,
    image: '../images/product-bp-monitor.svg', badge: 'sale',
    sizes: [], colors: ['White/Teal'],
    description: 'Blood glucose meter with 50 test strips, 50 lancets, adjustable lancing device and a soft-cover carrying case. 5-second reading, Bluetooth sync.',
    specs: { 'Reading time': '5 seconds', 'Sample': '0.5 ul blood', 'Memory': '500 readings', 'App sync': 'Bluetooth LE', 'Warranty': '5 years' },
  },
  {
    id: 95, sku: 'MED-095', name: 'HeartTrack ECG Home Monitor',
    category: 'Medical', tags: ['monitoring', 'ecg'], subCategory: 'Monitoring',
    price: 129.00, oldPrice: 179.00, rating: 4.6, reviewCount: 289, stock: 42,
    image: '../images/product-bp-monitor.svg', badge: 'new',
    sizes: [], colors: ['White'],
    description: 'FDA-cleared single-lead ECG for at-home use. Detects atrial fibrillation, bradycardia and tachycardia in 30 seconds; syncs a PDF report to your doctor.',
    specs: { 'Leads': 'Single lead', 'Duration': '30 seconds', 'AI classifier': 'Yes (Afib, brady, tachy)', 'Battery': 'Rechargeable 200 mAh', 'Warranty': '2 years' },
  },

  {
    id: 96, sku: 'MED-096', name: 'FoldGo Lightweight Wheelchair',
    category: 'Medical', tags: ['mobility'], subCategory: 'Aid & Mobility',
    price: 349.00, oldPrice: 449.00, rating: 4.5, reviewCount: 132, stock: 22,
    image: '../images/product-first-aid.svg', badge: null,
    sizes: ['Standard (46 cm)', 'Wide (51 cm)'], colors: ['Black', 'Navy'],
    description: 'Foldable lightweight aluminium wheelchair with dual brake system, flip-back armrests and swing-away footrests. Folds to fit most car boots.',
    specs: { 'Weight': '11.8 kg', 'Load rating': '120 kg', 'Seat width': '46 cm (wide 51)', 'Wheels': '24" pneumatic rear', 'Warranty': '2 years' },
  },
  {
    id: 97, sku: 'MED-097', name: 'StrideEase Rollator Walker',
    category: 'Medical', tags: ['mobility'], subCategory: 'Aid & Mobility',
    price: 149.00, oldPrice: 199.00, rating: 4.6, reviewCount: 214, stock: 68,
    image: '../images/product-first-aid.svg', badge: 'sale',
    sizes: [], colors: ['Silver', 'Burgundy'],
    description: 'Four-wheel rollator walker with a padded fold-down seat, ergonomic loop brakes and a zippered under-seat storage pouch.',
    specs: { 'Weight': '6.4 kg', 'Load rating': '135 kg', 'Wheels': '8" front swivel', 'Handles': 'Adjustable 80-95 cm', 'Warranty': '2 years' },
  },
  {
    id: 98, sku: 'MED-098', name: 'ReadyKit 150-piece First Aid Kit',
    category: 'Medical', tags: ['first-aid'], subCategory: 'Aid & Mobility',
    price: 39.99, oldPrice: 59.99, rating: 4.7, reviewCount: 921, stock: 320,
    image: '../images/product-first-aid.svg', badge: 'hot',
    sizes: ['150 pieces', '250 pieces (family)'], colors: ['Red'],
    description: 'Compact 150-piece first aid kit in a soft-shell zip case. Includes bandages, dressings, antiseptic wipes, gloves, scissors and a CPR face-shield.',
    specs: { 'Pieces': '150', 'Certification': 'ANSI Class A compliant', 'Case': 'Soft-shell zip', 'Weight': '0.9 kg', 'Warranty': '1 year' },
  },
  {
    id: 99, sku: 'MED-099', name: 'AeroMist Ultrasonic Nebulizer',
    category: 'Medical', tags: ['respiratory'], subCategory: 'Aid & Mobility',
    price: 79.99, oldPrice: 109.00, rating: 4.4, reviewCount: 156, stock: 84,
    image: '../images/product-first-aid.svg', badge: null,
    sizes: [], colors: ['White'],
    description: 'Portable ultrasonic nebulizer with adult and paediatric masks. Whisper-quiet at 30 dB, USB-C rechargeable, 40-minute continuous runtime.',
    specs: { 'Method': 'Ultrasonic', 'Noise': '<30 dB', 'Runtime': '40 min continuous', 'Particle size': '3-5 micron', 'Warranty': '2 years' },
  },
  {
    id: 100, sku: 'MED-100', name: 'ReliefWave TENS/EMS Unit',
    category: 'Medical', tags: ['therapy', 'pain-relief'], subCategory: 'Aid & Mobility',
    price: 59.99, oldPrice: 89.99, rating: 4.5, reviewCount: 421, stock: 132,
    image: '../images/product-first-aid.svg', badge: 'sale',
    sizes: [], colors: ['Grey'],
    description: 'Dual-channel TENS + EMS unit with 24 preset modes for pain relief, muscle recovery and physiotherapy. Rechargeable, comes with 8 electrode pads.',
    specs: { 'Channels': '2', 'Modes': '24 presets', 'Intensity': '20 levels', 'Battery': 'Rechargeable Li-ion', 'Warranty': '1 year' },
  },
];

/* ------------------------------------------------------------------
   Sub-category mapping — applied to every product on load. Keeping
   this as a separate map keeps the product objects skinny and lets
   automation tests query subcategories directly:
       Object.values(window.CATALOG).filter(p => p.subCategory === 'Audio')
   ------------------------------------------------------------------ */
window.SUBCATEGORIES = {
  /* Electronics (18) */
  1: 'Audio',        2: 'Wearables',   3: 'Audio',
  13: 'Smartphones', 14: 'Smartphones', 15: 'Tablets',
  16: 'Laptops',     17: 'Smartphones', 18: 'Laptops',
  19: 'Gaming',      20: 'Gaming',      21: 'Audio',
  22: 'Cameras',     23: 'Networking',  24: 'Displays',
  61: 'VR & AR',     62: 'E-Readers',   63: 'Audio',

  /* Fashion (22) */
  4: 'Outerwear',    5: 'Footwear',     6: 'Accessories',
  25: 'Denim',       26: 'Knitwear',    27: 'Footwear',
  28: 'Headwear',    29: 'Basics',      30: 'Knitwear',
  31: 'Footwear',    32: 'Headwear',    33: 'Outerwear',
  34: 'Outerwear',   35: 'Accessories', 36: 'Activewear',
  64: 'Outerwear',   65: 'Formalwear',  66: 'Trousers',
  67: 'Accessories', 68: 'Formalwear',  69: 'Outerwear',
  70: 'Activewear',

  /* Home (20) */
  7: 'Kitchen',      8: 'Lighting',     9: 'Kitchen',
  37: 'Wellness',    38: 'Appliances',  39: 'Kitchen',
  40: 'Kitchen',     41: 'Bedding',     42: 'Wellness',
  43: 'Decor',       44: 'Bath',        45: 'Kitchen',
  46: 'Decor',       47: 'Storage',     48: 'Kitchen',
  71: 'Appliances',  72: 'Bedding',     73: 'Lighting',
  74: 'Decor',       75: 'Kitchen',

  /* Books (25) */
  10: 'Programming', 11: 'Design',      12: 'Fiction',
  49: 'Self-help',   50: 'Fiction',     51: 'History',
  52: 'Business',    53: 'Programming', 54: 'Self-help',
  55: 'Memoir',      56: 'Programming', 57: 'Science',
  58: 'Self-help',   59: 'Fiction',     60: 'Design',
  76: 'Fiction',     77: 'Business',    78: 'Psychology',
  79: 'Fiction',     80: 'Memoir',      81: 'Philosophy',
  82: 'Business',    83: 'Programming', 84: 'Science',
  85: 'Self-help',
};

window.CATALOG.forEach((p) => {
  if (!p.subCategory) p.subCategory = window.SUBCATEGORIES[p.id] || null;
});

window.CATEGORIES = [
  { id: 'Electronics', name: 'Electronics', icon: 'laptop',      desc: 'Tech that keeps up with you' },
  { id: 'Fashion',     name: 'Fashion',     icon: 'shirt',       desc: 'Wardrobe essentials, elevated' },
  { id: 'Home',        name: 'Home',        icon: 'home',        desc: 'Beautiful spaces, thoughtful things' },
  { id: 'Books',       name: 'Books',       icon: 'book',        desc: 'Read, learn, escape' },
  { id: 'Medical',     name: 'Medical',     icon: 'stethoscope', desc: 'Instruments for home & clinic use' },
];

window.getProduct = function (id) {
  return window.CATALOG.find((p) => p.id === Number(id));
};
